package com.insit.mark.blog.common.persistence.model;

import java.io.Serializable;

/**
 *
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table role_resources
 *
 * @mbg.generated do_not_delete_during_merge
 */
public class RoleResourcesKey implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column role_resources.roleId
     *
     * @mbg.generated
     */
    private Integer roleid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column role_resources.resourcesId
     *
     * @mbg.generated
     */
    private Integer resourcesid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table role_resources
     *
     * @mbg.generated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column role_resources.roleId
     *
     * @return the value of role_resources.roleId
     *
     * @mbg.generated
     */
    public Integer getRoleid() {
        return roleid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column role_resources.roleId
     *
     * @param roleid the value for role_resources.roleId
     *
     * @mbg.generated
     */
    public void setRoleid(Integer roleid) {
        this.roleid = roleid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column role_resources.resourcesId
     *
     * @return the value of role_resources.resourcesId
     *
     * @mbg.generated
     */
    public Integer getResourcesid() {
        return resourcesid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column role_resources.resourcesId
     *
     * @param resourcesid the value for role_resources.resourcesId
     *
     * @mbg.generated
     */
    public void setResourcesid(Integer resourcesid) {
        this.resourcesid = resourcesid;
    }
}