package com.insit.mark.blog.common.persistence.dao;

import com.insit.mark.blog.common.persistence.model.RoleResourcesKey;

public interface RoleResourcesMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table role_resources
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(RoleResourcesKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table role_resources
     *
     * @mbg.generated
     */
    int insert(RoleResourcesKey record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table role_resources
     *
     * @mbg.generated
     */
    int insertSelective(RoleResourcesKey record);
}