server:
  port: 8080
  servlet:
    context-path: /blog-web
spring:
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/spring?useSSL=false&characterEncoding=utf8
    username: root
    password: admin
  redis:
    port: 6379
    host: 127.0.0.1
    timeout: 5000
    jedis:
      pool:
        max-active: 10
        max-wait: -1ms
        max-idle: 10
        min-idle: 1
  main:
    allow-bean-definition-overriding: true
  aop:
    auto: true
mybatis-plus:
  mapper-locations: classpath*:com/insit/mark/blog/**/**/mapping/*Mapper.xml, classpath*:com/insit/mark/blog/*/mapper/*Mapper.xml
  type-aliases-package: com.insit.mark.blog.common.persistence.model
