server:
  port: 8080
  servlet:
    context-path: /blog-web
spring:
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/spring?useSSL=false&characterEncoding=utf8
    username: root
    password: admin
  main:
    allow-bean-definition-overriding: true
sys:
  path: /
